### PR TITLE
8258378: Final nroff manpage update for JDK 16

### PR DESCRIPTION
**Pull request by magicus**
Before RC phase we need to ensure we have the final set of manpage updates published in OpenJDK.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8258378](https://bugs.openjdk.java.net/browse/JDK-8258378): Final nroff manpage update for JDK 16

### Reviewers
 * [Erik Joelsson](https://openjdk.java.net/census#erikj) (@erikj79 - **Reviewer**)
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk16 pull/142/head:pull/142`
`$ git checkout pull/142`

### CODE REVIEW

**Comment by magicus** [comment]
These updates have been made automatically from the markdown source files (which unfortunately is still closed-only).

**Review by erikj79 — APPROVED** [review]

**Review by dholmes-ora — APPROVED** [review]
Thanks for doing this Magnus! I had overlooked the fact we would need to re-run this in 2021 regardless of whether there were any content changes to propagate.

Cheers,
David

**Comment by magicus** [comment]
@dholmes-ora I did not think of that myself either. But the make target did the Right Thing. :-)

**Pull request closed without merging**
