### PR TITLE
8259719: ProblemList runtime/cds/appcds/jigsaw/modulepath/ModulePathAndCP_JFR.java on Windows

### PR DESCRIPTION
**Pull request by dcubed-ojdk**
This is a trivial fix to ProblemList runtime/cds/appcds/jigsaw/modulepath/ModulePathAndCP_JFR.java
on Windows in order to reduce the noise in the JDK16 CI.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8259719](https://bugs.openjdk.java.net/browse/JDK-8259719): ProblemList runtime/cds/appcds/jigsaw/modulepath/ModulePathAndCP_JFR.java on Windows

### Reviewers
 * [Per Liden](https://openjdk.java.net/census#pliden) (@pliden - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk16 pull/115/head:pull/115`
`$ git checkout pull/115`

### CODE REVIEW

**Comment by dcubed-ojdk** [comment]
Oooppps... forgot to click the "ready for review" button...

**Review by tschatzl — APPROVED** [review]

**Review by tschatzl — COMMENTED** [review]
... and trivial.

**Comment by dcubed-ojdk** [comment]
@tschatzl - Thanks for the fast review.

**Comment by dcubed-ojdk** [comment]
@tschatzl - The bot removed the "ready" label. Can you please re-review?

**Comment by dcubed-ojdk** [comment]
I don't think the bot liked it when I tried to integrate three separate PRs within a few seconds of each other...

**Review by pliden — APPROVED** [review]

**Comment by dcubed-ojdk** [comment]
@pliden - Thanks Per!

/integrate

**Pull request closed without merging**
