### PR TITLE
8257598: Clarify what component values are used in Record::equals

### PR DESCRIPTION
**Pull request by vicente-romero-oracle**
Please review this patch which modifies the spec for method java.lang.Record::equals. It states that the implementation of this method should use the record fields for the comparison instead of the accessors.

TIA,
Vicente

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8257598](https://bugs.openjdk.java.net/browse/JDK-8257598): Clarify what component values are used in Record::equals

### Reviewers
 * [Joe Darcy](https://openjdk.java.net/census#darcy) (@jddarcy - **Reviewer**) ⚠️ Review applies to 73e8ad5fa1f981a2d04dc087a57a60d2481e5de4
 * [Chris Hegarty](https://openjdk.java.net/census#chegar) (@ChrisHegarty - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk16 pull/5/head:pull/5`
`$ git checkout pull/5`

### CODE REVIEW

**Review by jddarcy — APPROVED** [review]
Looks fine.

**Review by ChrisHegarty — APPROVED** [review]
The change and test look good to me. Thanks Vicente.

I have just one minor comment on the location of the test. I know there is not always a clear and clean separation across component areas, but another possible location, for your consideration, is test/jdk/java/lang/reflect/record - which contains other runtime tests for records.

**Comment by vicente-romero-oracle** [comment]
> The change and test look good to me. Thanks Vicente.
> 
> I have just one minor comment on the location of the test. I know there is not always a clear and clean separation across component areas, but another possible location, for your consideration, is test/jdk/java/lang/reflect/record - which contains other runtime tests for records.

thanks for your comments, I have moved the test to another location

**Review by ChrisHegarty — APPROVED** [review]

**Pull request closed without merging**
