### PR TITLE
8254350: CompletableFuture.get may swallow InterruptedException

### PR DESCRIPTION
**Pull request by Martin-Buchholz**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8254350](https://bugs.openjdk.java.net/browse/JDK-8254350): CompletableFuture.get may swallow InterruptedException

### Reviewers
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**)
 * [Doug Lea](https://openjdk.java.net/census#dl) (@DougLea - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk16 pull/17/head:pull/17`
`$ git checkout pull/17`

### CODE REVIEW

**Review by AlanBateman — APPROVED** [review]
Previously reviewed for openjdk/jdk, looks good.

**Review by DougLea — APPROVED** [review]

**Comment by kezhuw** [comment]
@Martin-Buchholz @DougLea @AlanBateman Sorry for rough in.  After change `future.get()` to `future.get(1, TimeUnit.DAYS)`, `SwallowedInterruptedException` failed.

**Comment by Martin-Buchholz** [comment]
Thanks, Kezhu.  I filed:
https://bugs.openjdk.java.net/browse/JDK-8259796

**Pull request closed without merging**
