### PR TITLE
8258419: RSA cipher buffer cleanup

### PR DESCRIPTION
**Pull request by wangweij**
Some array allocation is not necessary, and the content can be cleaned.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8258419](https://bugs.openjdk.java.net/browse/JDK-8258419): RSA cipher buffer cleanup

### Reviewers
 * [Valerie Peng](https://openjdk.java.net/census#valeriep) (@valeriepeng - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk16 pull/26/head:pull/26`
`$ git checkout pull/26`

### CODE REVIEW

**Comment by valeriepeng** [comment]
Need a noreg-xxx label since there is no regression test.

**Comment by wangweij** [comment]
> Need a noreg-xxx label since there is no regression test.

`noreg-cleanup` Added. Thanks.

**Review by valeriepeng — APPROVED** [review]
Looks good.

**Pull request closed without merging**
