### PR TITLE
8260704: ParallelGC: oldgen expansion needs release-store for _end

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change that ensures MutableSpace::_end is updated after
everything else that is relevant when expanding, by using a release_store to
perform the update.  With this change the storestore that was added by
JDK-8257999 is no longer needed.

Testing:
mach5 tier1-3, tier5

/summary Move JDK-8257999 barrier to correct location.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8260704](https://bugs.openjdk.java.net/browse/JDK-8260704): ParallelGC: oldgen expansion needs release-store for _end

### Reviewers
 * [Thomas Schatzl](https://openjdk.java.net/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to 91d8be35abb6192858ca19bd8329d08e57f5794b
 * [Stefan Johansson](https://openjdk.java.net/census#sjohanss) (@kstefanj - **Reviewer**) ⚠️ Review applies to 91d8be35abb6192858ca19bd8329d08e57f5794b

### Download
`$ git fetch https://git.openjdk.java.net/jdk16 pull/141/head:pull/141`
`$ git checkout pull/141`

### CODE REVIEW

**Review by tschatzl — APPROVED** [review]
Lgtm

**Review by kstefanj — APPROVED** [review]
Looks good.

**Comment by kimbarrett** [comment]
Thanks @tschatzl and @kstefanj for reviews.

**Pull request closed without merging**
