### PR TITLE
8259007: This test printed a blank page

### PR DESCRIPTION
**Pull request by prsadhuk**
Backout JDK-8256264 fix.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * ⚠️ Failed to retrieve information on issue `8259007`.

### Reviewers
 * [Phil Race](https://openjdk.java.net/census#prr) (@prrace - **Reviewer**)
 * [Sergey Bylokhov](https://openjdk.java.net/census#serb) (@mrserb - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk16 pull/80/head:pull/80`
`$ git checkout pull/80`

### CODE REVIEW

**Review by prrace — APPROVED** [review]
I assume you tested this does indeed fix the regressipn ?
Approving on that understanding.

**Review by mrserb — APPROVED** [review]

**Comment by mrserb** [comment]
The fix for JDK-8256264 made an assumption that moveTo/lineTo methods are always wrapped by the beginPath/endPath. So that fix sets the scale in the beginPath/endPath and correct the passed parameters in the moveTo/lineTo. But this new code in the moveTo/lineTo does not work well if the beginPath was not called.

**Comment by prsadhuk** [comment]
> 
> 
> I assume you tested this does indeed fix the regressipn ?
> Approving on that understanding.

Yes, it does fix in my testing and I also got confirmation from EG that this patch fix the issues.

**Pull request closed without merging**
