### PR TITLE
8257468: runtime/whitebox/TestWBDeflateIdleMonitors.java fails with Monitor should be deflated.: expected true to equal false

### PR DESCRIPTION
**Pull request by dcubed-ojdk**
This is a trivial test fix to add a retry loop to the code that exercises the
WhiteBox deflateIdleMonitors() API. The failure reported in JDK-8257468
has only been seen one time in a Same-Binary-Run. I have not seen this
failure in my lab with my stress testing nor has it been seen in Mach5.

Tested with the modified test.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8257468](https://bugs.openjdk.java.net/browse/JDK-8257468): runtime/whitebox/TestWBDeflateIdleMonitors.java fails with Monitor should be deflated.: expected true to equal false

### Reviewers
 * [Harold Seigel](https://openjdk.java.net/census#hseigel) (@hseigel - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk16 pull/67/head:pull/67`
`$ git checkout pull/67`

### CODE REVIEW

**Review by hseigel — APPROVED** [review]
The changes look good and trivial.
Harold

**Comment by dcubed-ojdk** [comment]
@hseigel - Thanks for the fast review!

**Comment by dcubed-ojdk** [comment]
Mach5 Tier1 passed and the new test passed on all four platforms in Tier1.

/integrate

**Pull request closed without merging**
