### PR TITLE
8258094: AIX build fails after 8257602

### PR DESCRIPTION
**Pull request by mgronlun**
Greetings,

AIX/xlc does not support the THREAD_LOCAL macro.

This change moves more involved event posting from gc/shared into JFR.

Thanks
Markus

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8258094](https://bugs.openjdk.java.net/browse/JDK-8258094): AIX build fails after 8257602

### Reviewers
 * [Richard Reingruber](https://openjdk.java.net/census#rrich) (@reinrich - Committer) ⚠️ Review applies to aed88806896420587a4b8bd741cd12ac9fa4135c
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**) ⚠️ Review applies to aed88806896420587a4b8bd741cd12ac9fa4135c
 * [Erik Gahlin](https://openjdk.java.net/census#egahlin) (@egahlin - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk16 pull/11/head:pull/11`
`$ git checkout pull/11`

### CODE REVIEW

**Review by reinrich — APPROVED** [review]
Hi Markus,

this fix looks good to me. Aix build succeeds with it.

Thanks for fixing,
Richard.

**Review by tstuefe — APPROVED** [review]
Looks fine. Thanks for fixing.

**Review by egahlin — APPROVED** [review]

**Comment by mgronlun** [comment]
Thanks @reinrich , @tstuefe and @egahlin for your reviews!

**Pull request closed without merging**
